import { useInView } from "@/hooks/useInView";
import QlikEmbed from "@/components/QlikEmbed";
import { qlikConfig } from "@/config/qlikConfig";
import { Percent, Zap, TrendingDown } from "lucide-react";

const QualityAnalysisSection = () => {
  const { ref, isInView } = useInView({ threshold: 0.1 });

  return (
    <section id="quality" className="py-24 bg-background" ref={ref}>
      <div className="section-container">
        {/* Section Header */}
        <div className={`mb-16 ${isInView ? "animate-fade-up" : "opacity-0"}`}>
          <span className="text-secondary font-semibold text-sm uppercase tracking-wider">
            Section 03
          </span>

          <h2 className="text-4xl md:text-5xl font-bold mt-2 mb-4">
            Quality Analysis
          </h2>

          <p className="text-muted-foreground text-lg max-w-2xl">
            Exploring quality metrics including NOK ratios, torque analysis, and identifying
            areas for quality improvement.
          </p>
        </div>

        {/* KPI Cards */}
        <div
          className={`grid grid-cols-1 md:grid-cols-2 gap-6 mb-12 ${
            isInView ? "animate-fade-up delay-100" : "opacity-0"
          }`}
        >
          <div className="kpi-card">
            <Percent className="w-8 h-8 text-secondary mx-auto mb-3" />

            <p className="text-muted-foreground text-sm mb-1">
              NOK pieces ratio
            </p>

            <QlikEmbed
              objectId={qlikConfig.charts.qualityAnalysis.nokRatio}
              height="90px"
            />
          </div>

          <div className="kpi-card">
            <Zap className="w-8 h-8 text-secondary mx-auto mb-3" />

            <p className="text-muted-foreground text-sm mb-1">
              Average NOK Torque
            </p>

            <QlikEmbed
              objectId={qlikConfig.charts.qualityAnalysis.avgNokTorque}
              height="90px"
            />
          </div>
        </div>

        {/* Charts Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 mb-8">
          <div
            className={`chart-container p-4 ${
              isInView ? "animate-slide-in-left delay-200" : "opacity-0"
            }`}
          >
            <h3 className="font-semibold mb-4 text-lg">
              NOK Ratio Over Time
            </h3>

            <QlikEmbed
              objectId={qlikConfig.charts.qualityAnalysis.nokRatioOverTime}
              height="250px"
            />
          </div>

          <div
            className={`chart-container p-4 ${
              isInView ? "animate-slide-in-right delay-200" : "opacity-0"
            }`}
          >
            <h3 className="font-semibold mb-4 text-lg">
              Pieces Generating Non Torque
            </h3>

            <QlikEmbed
              objectId={qlikConfig.charts.qualityAnalysis.paretoChart}
              height="250px"
            />
          </div>
        </div>

        <div
          className={`chart-container p-4 mb-12 ${
            isInView ? "animate-fade-up delay-300" : "opacity-0"
          }`}
        >
          <h3 className="font-semibold mb-4 text-lg">
            Torque vs Operating Time
          </h3>

          <QlikEmbed
            objectId={qlikConfig.charts.qualityAnalysis.torqueVsOperatingTime}
            height="400px"
          />
        </div>

        {/* Narrative Box */}
        <div
          className={`narrative-box ${
            isInView ? "animate-fade-up delay-400" : "opacity-0"
          }`}
        >
          <h4 className="font-semibold text-lg mb-3 flex items-center gap-2">
            <span className="w-2 h-2 bg-secondary rounded-full" />
            Key Insights
          </h4>

          <p className="text-muted-foreground leading-relaxed mb-4">
            Taking a look at NOK torque, we can observe that ratios are more than
            decent. Also, it should be convenient to keep an eye on the pieces
            generated by the operation code 1, since it does most of them.
          </p>

          <p className="text-muted-foreground leading-relaxed">
            Looking at the scatter plot we can understand that since in terms of
            torque we have a good group at around 350, in terms of angle there is a
            huge variety of pieces, that vary between 30 and 44. It is definitely a
            metric that should be controlled closely.
          </p>
        </div>
      </div>
    </section>
  );
};

export default QualityAnalysisSection;